# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on: push

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  lint:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - name: testing lin
        run: |
          echo "lin"

  build:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - name: testing
        run: |
          ls
