# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HERE_MAPS_TOKEN: ${{ secrets.HERE_MAPS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose build
        run: |
          docker-compose build
