# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on: push

jobs:
  lint-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install flake8
        run: |
          python -m pip install flake8
      - name: Run lint with flake8
        run: |
          flake8 server/src --show-source --count --statistics --max-line-length=120

  lint-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource.sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-latest
    env:
      HERE_MAPS_TOKEN: ${{ secrets.HERE_MAPS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: docker-compose build
        run: |
          docker-compose build
